### ISSUE TITLE
Missing utils

### ISSUE THREAD

**Issue by TsuTikgiau** [Xingyu-Lin/mbpo_pytorch#1]
Hello,
Thanks for your awesome pytorch reimplementation! I'd like to have a try but I notice that I cannot find the [utils](https://github.com/Xingyu-Lin/mbpo_pytorch/blob/main/main_mbpo.py#L14) in the main_mbpo.py file. May I have your help? Thanks!

**Comment by TsuTikgiau** [comment]
Oh, I just noticed that utils is actually not used. I commented it out and the script is runnable now. Thank you!

**Comment by Xingyu-Lin** [comment]
Issue is resolved.
